# Host vars for Bitcoin Core Node

#
# linux-system-roles.storage vars
#
storage_pools:
  - name: vg_bitcoin
    disks:
      - sdb
    type: lvm
    grow_to_fill: true
    volumes:
      - name: lv_bitcoin
        size: "98%" # https://github.com/linux-system-roles/storage/tree/1.19.1#:~:text=NOTE:%20The%20requested%20volume%20size%20may%20be%20reduced%20as%20necessary%20so%20the%20volume%20can%20fit%20in%20the%20available%20pool%20space%2C%20but%20only%20if%20the%20required%20reduction%20is%20not%20more%20than%202%%20of%20the%20requested%20volume%20size.
        fs_type: ext4
        mount_point: /var/lib/bitcoin
        mount_options: "defaults,noatime"
        mount_user: bitcoin
        mount_group: bitcoin
        mount_mode: "0750"
        state: present

#
# Bitcoin Core configuration
#
bitcoin_core_version: "30.0"
# SHA256 for bitcoin-{{ bitcoin_core_version }}-x86_64-linux-gnu.tar.gz in format "sha256:<hex>"
bitcoin_core_tarball_sha256: "sha256:00964ae375084113b1162f2f493b9372421608af23539766e315a3cb0ee54248"
bitcoin_user: bitcoin
bitcoin_group: bitcoin
bitcoin_data_dir: /var/lib/bitcoin
bitcoin_config_path: /var/lib/bitcoin/bitcoin.conf

bitcoin_rpcuser: bitcoin
bitcoin_rpcpassword: "{{ vault_bitcoin_rpcpassword }}"
bitcoin_server: true
bitcoin_txindex: true
bitcoin_dbcache: 1024
