# Host vars for Bitcoin Core Node

#
# robertdebock.bootstrap vars
#
bootstrap_become: true

#
# robertdebock.storage vars
#
storage_partitions:
  - name: /dev/sdb
    number: 1
    part_end: 100%
    label: gpt
storage_volumegroups:
  - name: vg_bitcoin
    devices:
      - /dev/sdb1
storage_volumes:
  - name: lv_bitcoin
    vg: vg_bitcoin
    size: "+100%FREE"
storage_filesystems:
  - name: /dev/vg_bitcoin/lv_bitcoin
    fstype: ext4
storage_mounts:
  - name: /var/lib/bitcoin
    src: /dev/vg_bitcoin/lv_bitcoin
    owner: bitcoin
    group: bitcoin
    mode: "0750"
    opts: "defaults,noatime"

#
# Bitcoin Core configuration
#
bitcoin_core_version: "30.0"
# SHA256 for bitcoin-{{ bitcoin_core_version }}-x86_64-linux-gnu.tar.gz in format "sha256:<hex>"
bitcoin_core_tarball_sha256: "sha256:00964ae375084113b1162f2f493b9372421608af23539766e315a3cb0ee54248"
bitcoin_user: bitcoin
bitcoin_group: bitcoin
bitcoin_data_dir: /var/lib/bitcoin
bitcoin_config_path: /var/lib/bitcoin/bitcoin.conf

bitcoin_rpcuser: bitcoin
bitcoin_rpcpassword: "{{ vault_bitcoin_rpcpassword }}"
bitcoin_server: true
bitcoin_txindex: true
bitcoin_dbcache: 1024
