#
# Salt Project onedir packages (recommended by Salt Install Guide for production: LTS)
# https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-rpm.html
#

salt_repo_file_url: "https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo"

# Pin to an LTS point release by using package-version suffixes
salt_version: "3006.17"

salt_packages:
  - "salt-master-{{ salt_version }}"
  - "salt-minion-{{ salt_version }}"
  - "salt-ssh-{{ salt_version }}"
  - git

salt_onedir_pip_packages:
  - GitPython

salt_gitfs_provider: gitpython
salt_git_repo_url: "https://github.com/ded-isshin/infrastructure-home.git"
salt_git_branch: main
salt_gitfs_root: salt
salt_git_pillar_root: pillar
